fun foo() {
    throw Exception()
    print("Unreachable!")
}
